server:
  port: 8888

spring:
  #  profiles:
  #    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/tlrru/IdeaProjects/msa-discovery
        git: #default
          uri: https://github.com/tlrruddbs/spring-cloud-config
          default-label: main
        #          username: <github-id>
        #          password: <gihub-accessToken>
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

